//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NotesDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotesDetail()
        {
            this.Downloads = new HashSet<Download>();
            this.NotesAttachments = new HashSet<NotesAttachment>();
            this.Reviews = new HashSet<Review>();
            this.SpamReports = new HashSet<SpamReport>();
        }
    
        public int ID { get; set; }
        public int SellerID { get; set; }
        
        public string Title { get; set; }
        public string Description { get; set; }
        public string DisplayPicture { get; set; }
        public string NotePreview { get; set; }
        public int CategoryID { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> NumberOfPages { get; set; }
        public bool IsPaid { get; set; }
        public int Price { get; set; }
        public System.DateTime PublishedDate { get; set; }
        public int ActionedBy { get; set; }
        public string AdminRemarks { get; set; }
        public string Status { get; set; }
        public string UniversityName { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string Course { get; set; }
        public string CourseCode { get; set; }
        public string Professor { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Download> Downloads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotesAttachment> NotesAttachments { get; set; }
        public virtual Type Type { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpamReport> SpamReports { get; set; }
    }
}
