//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public int AgainstDownloadsID { get; set; }
        public int ReviewedByUserID { get; set; }
        public int ReviewedNoteID { get; set; }
        public int Ratings { get; set; }
        public string Comments { get; set; }
        public System.DateTime DateReviewed { get; set; }
        public int ReviewedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Download Download { get; set; }
        public virtual NotesDetail NotesDetail { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
