//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpamReport
    {
        public int SpamReportID { get; set; }
        public int NoteID { get; set; }
        public int ReportedByUserID { get; set; }
        public int AgainstDownloadID { get; set; }
        public Nullable<System.DateTime> DateReported { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        public virtual Download Download { get; set; }
        public virtual NotesDetail NotesDetail { get; set; }
        public virtual User User { get; set; }
    }
}
