//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesMarketplace
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class SystemConfiguration
    {
        public int ID { get; set; }
        public string key { get; set; }
        public string Value { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public bool IsActive { get; set; }


        [NotMapped]
        public string SupportEmail { get; set; }

        [NotMapped]
        public string SupportPhone { get; set; }

        [NotMapped]
        public string EmailAddress { get; set; }

        [NotMapped]
        public string Facebook { get; set; }

        [NotMapped]
        public string Twitter { get; set; }

        [NotMapped]
        public string Linkedin { get; set; }

        [NotMapped]
        public string NotesPreview { get; set; }

        [NotMapped]
        public string ProfilePicture { get; set; }




        [NotMapped]
        public HttpPostedFileBase file1 { get; set; }
        
        [NotMapped]
        public HttpPostedFileBase file2 { get; set; }
    }
}
